name: alioss-update-auto
env:
  TZ: Asia/Shanghai

on:
  schedule:
    - cron: "0 20 2 * *"          # 每月2号20:00 UTC（北京时间凌晨4点）
  workflow_dispatch:              # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y certbot python3-pip
          pip3 install requests oss2

      - name: Issue certificate via DNSPod (Python hook)
        env:
          DP_SecretId: ${{ secrets.DP_SecretId }}
          DP_SecretKey: ${{ secrets.DP_SecretKey }}
        run: |
          chmod +x dnspod_auth.py
          mkdir -p ~/letsencrypt
          certbot certonly -d "${{ secrets.DOMAIN }}" \
            --manual --preferred-challenges dns \
            --manual-auth-hook "./dnspod_auth.py" \
            --manual-cleanup-hook "./dnspod_auth.py clean" \
            --agree-tos --email ${{ secrets.EMAIL }} \
            --non-interactive \
            --config-dir ~/letsencrypt/config \
            --work-dir ~/letsencrypt/work \
            --logs-dir ~/letsencrypt/logs

      - name: Run OSS Cert Update
        run: |
          CERT_PATH="$HOME/letsencrypt/config/live/${{ secrets.DOMAIN }}"
          export CERTIFICATE="$(cat $CERT_PATH/fullchain.pem)"
          export PRIVATE_KEY="$(cat $CERT_PATH/privkey.pem)"
          python oss_update.py \
            --access-key-id "${{ secrets.ACCESS_KEY_ID }}" \
            --access-key-secret "${{ secrets.ACCESS_KEY_SECRET }}" \
            --endpoint "${{ secrets.ENDPOINT }}" \
            --bucket-name "${{ secrets.BUCKET_NAME }}" \
            --target-cname "${{ secrets.DOMAIN }}" \
            --private-key "$PRIVATE_KEY" \
            --certificate "$CERTIFICATE"
